Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning


ModuleLoader:
  ModuleDirectoryPath: "../modules"
  Modules:
    - "Neuron.Modules.TestModule/bin/Debug/net10.0/Neuron.Modules.TestModule.dll"