Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
AllowedHosts: "*"

OpenId:
  Server:
    AuthorizationEndpointUris:
      - connect/authorize
      - connect/authorize/accept
      - connect/authorize/deny
    TokenEndpointUris: [ connect/token ]
    EndSessionEndpointUris: [ connect/endsession ]
    UserInfoEndpointUris: [ connect/userinfo ]
    IntrospectionEndpointUris: [ connect/introspect ]
    GrantTypes:
      - authorization_code
      - refresh_token
    ResponseTypes: [ code ]
    Scopes: [ openid, profile, email, roles, offline_access ]
